### ISSUE TITLE
Testing all

### ISSUE THREAD

**Issue by skorovDev** [skorovDev/test_landing_thulby#14]

**Comment by skorovDev** [comment]
@VitaliiChernelivskyi 

https://test-landing-thulby.vercel.app/

**Comment by skorovDev** [comment]
![image](https://user-images.githubusercontent.com/98920475/152973455-e5fe0780-89da-4989-a395-ec2110e288a5.png)

**Comment by VitaliiChernelivskyi** [comment]
1.Logo header Якість ! 
![image](https://user-images.githubusercontent.com/98636866/152973902-97a75502-9640-4ee8-86b8-550ad4bd20fb.png)

2.На Pc перебиваються animations ! 
![image](https://user-images.githubusercontent.com/98636866/152973703-e52f9804-ae9e-43a3-8282-e41ecca843c0.png)

3.Hе працює кнопк instagram в  header ! 
![image](https://user-images.githubusercontent.com/98636866/152974039-79507572-c40a-4623-b41c-2c52a2d16948.png)

4.В мобільній версії горизонтальний  скрол!
![image](https://user-images.githubusercontent.com/98636866/152974341-1cbf3cc1-adcc-4e6f-aa57-f35244f0e9ca.png)

**Comment by VitaliiChernelivskyi** [comment]
1

**Comment by VitaliiChernelivskyi** [comment]
( На Pc перебиваються animations !) Все добре

**Comment by VadymTsymbaliuk** [comment]
Вніс правки стосовно зауважень, замінив лого з png => svg
пофіксив анімацію розвороту,
додав посилання на instagram.com в кнопку хедера,
пофіксив горизонтальний скрол, який зʼявлявся при введенні невалідних даних в форму (шляхом додавання атрибуту user-scalable=no до viewport)
